### ISSUE TITLE
Silhouette not working for Neos.NodeTypes:Text

### ISSUE THREAD

**Issue by bstrilziw** [sitegeist/Sitegeist.Silhouettes#10]
The pre-defined silhouettes (text.plain, text.block, text.free) and my own are working fine with everything but `Neos.NodeTypes:Text`. 

```
'Neos.NodeTypes:Text':
  properties:
    text:
      options:
        silhouette: 'text.free'
```

(referencing https://github.com/sitegeist/Sitegeist.Silhouettes/blob/master/Configuration/Settings.yaml#L58)

We've got this with 2 Neos 5.2 sites. Can anyone reproduce this?
