### ISSUE TITLE
Inherit from another Silhouette

### ISSUE THREAD

**Issue by paavo** [sitegeist/Sitegeist.Silhouettes#11]
Is there a way, to inherit from another Silhouette?
Maybe @mficzel has an idea?

```
Sitegeist:
  Silhouettes:
    properties:
      vendor:
        image:

          # vendor.image.plain
          plain:
            type: Neos\Media\Domain\Model\ImageInterface
            ui:
              label: 'Image'
              reloadIfChanged: true
              inspector:
                group: image

          # vendor.image.square
          square:
            # inherit from another silhouette
            options:
              silhouette: 'vendor.image.plain'
            # customize settings
            ui:
              label: 'Image square'
```

**Comment by mficzel** [comment]
No that is a bit to much since it would mean inheritence on two axis (NodeTyoes and Silhouettes). 
I do not dare to predict what would happen it we would implement this-

You can use yaml anchors if the silhouttes are in a single file like this:

```
Sitegeist:
  Silhouettes:
    properties:
      vendor:
        image:
          plain:  &image-plain
            type: Neos\Media\Domain\Model\ImageInterface
            ui:
              label: 'Image'
              reloadIfChanged: true
              inspector:
                group: image
          square:
            <<: *image-plain
            options:
              silhouette: 'vendor.image.plain'
            ui:
              label: 'Image square'
```
That would allow to create a set of related silhouettes
