### ISSUE TITLE
Feature: Use multiple Silhouettes

### ISSUE THREAD

**Issue by paavo** [sitegeist/Sitegeist.Silhouettes#12]
I'd love to have multiple Silhouettes for one single property. 
Or is there already a way @mficzel ?

```
    image:
      options:
        silhouette:
          - 'vendor.image.square'
          - 'vendor.message.sync'
```
