### ISSUE TITLE
It's not possible to use translations

### ISSUE THREAD

**Issue by pmaas** [sitegeist/Sitegeist.Silhouettes#2]
Currently it is not possible to add `i18n` labels to `Settings.yaml`:

<img width="313" alt="Bildschirmfoto 2019-05-15 um 18 04 48" src="https://user-images.githubusercontent.com/2778669/57791240-aa467c80-773c-11e9-9d48-ce01a9c2a14c.png">

Would be nice if this would be possible :)

**Comment by breadlesscode** [comment]
Any plans here? This is a important feature I think..

**Comment by breadlesscode** [comment]
@pmaas You have to use the complete translation path in your silhouette setting.

For example:

```
Sitegeist:
  Silhouettes:
    properties:
      vendor:
        values:
          aspectRatio:
            type: string
            defaultValue: ''
            ui:
              label: 'Vendor:NodeTypes.Content.Element:properties.imageFormat'
              reloadIfChanged: true
              inspector:
                group: 'options'
                editor: 'Neos.Neos/Inspector/Editors/SelectBoxEditor'
                editorOptions:
                  placeholder: 'Neos.Neos:Main:choose'
```
