### ISSUE TITLE
It's not possible to use ImageInterface as property type

### ISSUE THREAD

**Issue by pmaas** [sitegeist/Sitegeist.Silhouettes#3]
The use of `Neos\Media\Domain\Model\ImageInterface` as property type results in a `Missing editor definition` error.

```
Sitegeist:
  Silhouettes:
    properties:
      vendor:
        image:
          plain:
            type: Neos\Media\Domain\Model\ImageInterface
            ui:
              reloadIfChanged: true
              inspector:
                group: 'image'
                position: 10
```
```
  properties:
    image:
      ui:
        label: i18n
        inspector:
          group: 'image'
          position: 10
      options:
        silhouette: 'vendor.image.plain'
```
<img width="312" alt="Bildschirmfoto 2019-05-15 um 21 18 09" src="https://user-images.githubusercontent.com/2778669/57803039-b429a900-7757-11e9-9c57-be576cfcf740.png">
