### ISSUE TITLE
Silhouettes is applied after configuration enrichment, but needs to be applied first

### ISSUE THREAD

**Issue by rolandschuetz** [sitegeist/Sitegeist.Silhouettes#4]
The [NodeTypeConfigurationEnrichmentAspect](https://github.com/neos/neos-development-collection/blob/master/Neos.Neos/Classes/Aspects/NodeTypeConfigurationEnrichmentAspect.php#L59) enriches the property configuratiuon with dataType-specific default values. This is triggered via `@Flow\Around("method(Neos\ContentRepository\Domain\Model\NodeType->__construct())").

Sihouettes postprocess is called after the media enrichment and therefore misses the vital defaults.

This is the reason for the following two bugs:
#2 It's not possible to use translations
#3 It's not possible to use ImageInterface as property type

Manual Test Case:
Settings.yaml
```
Sitegeist:
  Silhouettes:
    properties:
      viennajs:
        image:
          type: Neos\Media\Domain\Model\ImageInterface
          ui:
            label: i18n
            reloadIfChanged: true
            inspector:
              group: 'general'
              position: 50
```

Test Properties:
```
  properties:
    image:
      options:
        silhouette: 'viennajs.image'
    imageHalf:
      type: Neos\Media\Domain\Model\ImageInterface
      ui:
        inspector:
          position: 50
      options:
        silhouette: 'viennajs.image'
    imageFull:
      type: Neos\Media\Domain\Model\ImageInterface
      ui:
        label: i18n
        reloadIfChanged: true
        inspector:
          group: 'general'
          position: 50
```

Expected result for all three cases:
```
    image:
      type: Neos\Media\Domain\Model\ImageInterface
      ui:
        label: Image
        reloadIfChanged: true
        inspector: { editorOptions: { fileUploadLabel: 'Neos.Neos:Main:choose', maximumFileSize: null, features: { crop: true, upload: true, mediaBrowser: true, resize: false }, crop: { aspectRatio: { options: { square: { width: 1, height: 1, label: Square }, fourFive: { width: 4, height: 5 }, fiveSeven: { width: 5, height: 7 }, twoThree: { width: 2, height: 3 }, fourThree: { width: 4, height: 3 }, sixteenNine: { width: 16, height: 9 } }, enableOriginal: true, allowCustom: true, locked: { width: 0, height: 0 } } } }, typeConverter: Neos\Neos\Ui\TypeConverter\UiDependentImageSerializer, editor: Neos.Neos/Inspector/Editors/ImageEditor, group: general, position: 50 }
```

Actual result:
```
    image:
      type: Neos\Media\Domain\Model\ImageInterface
      ui:
        label: i18n
        reloadIfChanged: true
        inspector: { group: general, position: 50 }
      options:
        silhouette: viennajs.image
    imageHalf:
      type: Neos\Media\Domain\Model\ImageInterface
      ui:
        label: i18n
        reloadIfChanged: true
        inspector: { group: general, position: 50, editorOptions: { fileUploadLabel: 'Neos.Neos:Main:choose', maximumFileSize: null, features: { crop: true, upload: true, mediaBrowser: true, resize: false }, crop: { aspectRatio: { options: { square: { width: 1, height: 1, label: Square }, fourFive: { width: 4, height: 5 }, fiveSeven: { width: 5, height: 7 }, twoThree: { width: 2, height: 3 }, fourThree: { width: 4, height: 3 }, sixteenNine: { width: 16, height: 9 } }, enableOriginal: true, allowCustom: true, locked: { width: 0, height: 0 } } } }, typeConverter: Neos\Neos\Ui\TypeConverter\UiDependentImageSerializer, editor: Neos.Neos/Inspector/Editors/ImageEditor }
      options:
        silhouette: viennajs.image
    imageFull:
      type: Neos\Media\Domain\Model\ImageInterface
      ui:
        label: 'ViennaJS.Site:NodeTypes.Document.Event:properties.imageFull'
        reloadIfChanged: true
        inspector: { editorOptions: { fileUploadLabel: 'Neos.Neos:Main:choose', maximumFileSize: null, features: { crop: true, upload: true, mediaBrowser: true, resize: false }, crop: { aspectRatio: { options: { square: { width: 1, height: 1, label: Square }, fourFive: { width: 4, height: 5 }, fiveSeven: { width: 5, height: 7 }, twoThree: { width: 2, height: 3 }, fourThree: { width: 4, height: 3 }, sixteenNine: { width: 16, height: 9 } }, enableOriginal: true, allowCustom: true, locked: { width: 0, height: 0 } } } }, typeConverter: Neos\Neos\Ui\TypeConverter\UiDependentImageSerializer, editor: Neos.Neos/Inspector/Editors/ImageEditor, group: general, position: 50 }
```
